name: Easy WireGuard Connection
description: Easy WireGuard Connection Setup

inputs:
  WG_CONFIG_FILE:
    description: WireGuard (wg-quick) configuration file
    required: true

runs:
    using: composite
    steps:
        - run: |
              sudo apt install resolvconf
              sudo apt install wireguard
              echo "${{ inputs.WG_CONFIG_FILE }}" > wg0.conf
              sudo chmod 600 wg0.conf
              echo "setting config"
              sudo wg-quick up ./wg0.conf && echo "wg-quick setup successful"
          shell: bash

branding:
  icon: shield
  color: red
